# Kohonen Network
1703176

014-05-2023

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random

In [ ]:
l_r = 0.5
radius = 3
epoch = 80
input = np.array([1,2,3,4,5,6,7,8,9,10])
neurons = 4
weights = np.random.rand(neurons)

print(weights)

for i in range(epoch):
    input_vec = input[random.randint(0, len(input)-1)]
    win = 0
    windis = np.abs(weights[0]-input_vec)

    # print(input_vec)
    # print(windis)

    for j in range(1, neurons):
        neuron_distance = np.abs(weights[j]-input_vec)
        # print(neuron_distance)
        if neuron_distance < windis:
            win = j
            windis = neuron_distance

    for j in range (neurons):
        distance_to_win = np.abs(j-win)
        # print(distance_to_winner)
        if distance_to_win <= radius:
            neighbor_factor = 1 - (distance_to_win/radius)
            weights[j] += l_r * neighbor_factor * (input_vec - weights[j])

            print(weights)


[0.58708467 0.04712924 0.54694942 0.10476734]
[3.79354233 0.04712924 0.54694942 0.10476734]
[3.79354233 2.36475283 0.54694942 0.10476734]
[3.79354233 2.36475283 1.62245785 0.10476734]
[3.79354233 2.36475283 1.62245785 0.10476734]
[3.89677117 2.36475283 1.62245785 0.10476734]
[3.89677117 2.90983522 1.62245785 0.10476734]
[3.89677117 2.90983522 2.01871488 0.10476734]
[3.89677117 2.90983522 2.01871488 0.10476734]
[3.89677117 2.90983522 2.01871488 0.10476734]
[3.89677117 2.59152935 2.01871488 0.10476734]
[3.89677117 2.59152935 1.67914325 0.10476734]
[3.89677117 2.59152935 1.67914325 0.55238367]
[3.94838558 2.59152935 1.67914325 0.55238367]
[3.94838558 3.06101957 1.67914325 0.55238367]
[3.94838558 3.06101957 2.06595271 0.55238367]
[3.94838558 3.06101957 2.06595271 0.55238367]
[6.97419279 3.06101957 2.06595271 0.55238367]
[6.97419279 5.37401304 2.06595271 0.55238367]
[6.97419279 5.37401304 3.38829392 0.55238367]
[6.97419279 5.37401304 3.38829392 0.55238367]
[6.9870964  5.37401304 3.38829392 

# Hopfield Neetwork


In [ ]:
pattern0 =  [-1, 1, -1, 1]
pattern1 =  [1, 1, 1, -1]
pattern2 =  [-1, -1, -1, 1]

w00 = 0
w11 =0
w22 = 0
w33 = 0

w01 = w10 = (pattern0[0]*pattern0[1]) + (pattern1[0]*pattern1[1]) + (pattern2[0]*pattern2[1])
w02 = w20 = (pattern0[0]*pattern0[2]) + (pattern1[0]*pattern1[2]) + (pattern2[0]*pattern2[2])
w03 = w30 = (pattern0[0]*pattern0[3]) + (pattern1[0]*pattern1[3]) + (pattern2[0]*pattern2[3])
w12 = w21 = (pattern0[1]*pattern0[2]) + (pattern1[1]*pattern1[2]) + (pattern2[1]*pattern2[2])
w13 = w31 = (pattern0[1]*pattern0[3]) + (pattern1[1]*pattern1[3]) + (pattern2[1]*pattern2[3])
w23 = w32 = (pattern0[2]*pattern0[3]) + (pattern1[2]*pattern1[3]) + (pattern2[2]*pattern2[3])

weights = [
    [w00, w01, w02, w03],
    [w10, w11, w12, w13],
    [w20, w21, w22, w23],
    [w30, w31, w32, w33]
]

print(weights)

[[0, 1, 3, -3], [1, 0, 1, -1], [3, 1, 0, -3], [-3, -1, -3, 0]]
